
export const INTERACTIONMODE = {
    DEFAULT: 'DEFAULT',
    CONVERSATIONMODE: 'CONVERSATION',
    COMPOSERMODE:'COMPOSER',
    OPTIMIZERMODE: 'OPTIMIZER',
}

export const INTERACTOINWINDOWTABS = {
    AICONVERSATION: 'AI Conversation',
    AICOMPOSER: 'AI Composer',
    AIOPTIMIZER: 'AI Optimizer',
}

export const INTERACTIONSPEAKER= {
    AI: 'AI',
    USER: 'USER',
}